baseURL = "http://example.org/"
languageCode = "en-us"
title = "SauberEco"
theme = "ananke"

[params]
  background_color_class = "bg-light-green"     # Hintergrundfarbe ändern
  cover_dimming_class = "bg-black-30"           # Abdunkelung des Header-Bildes
  featured_image_class = "cover bg-center"      # Layout des Titelbildes
  custom_css = ["css/custom.css"] 

[menu]
  [[menu.main]]
    identifier = "ueber_uns"
    name = "Über uns"
    url = "/ueber_uns/"
    weight = 1

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2

  [[menu.main]]
    identifier = "produkte"
    name = "Produkte"
    url = "/produkte/"
    weight = 3

  [[menu.main]]
    identifier = "fallstudien"
    name = "Fallstudien"
    url = "/fallstudien/"
    weight = 4

  [[menu.main]]
    identifier = "insights"
    name = "Insights"
    url = "/insights/"
    weight = 5

  [[menu.main]]
    identifier = "kontakt"
    name = "Kontakt"
    url = "/kontakt/"
    weight = 6
